---
name: "Flake Check Action"
run-name: "nfc"
on:
  workflow_dispatch: 
  push:
  pull_request:
    types: [
      opened,
      edited,
      synchronize,
      reopened
    ]
    
jobs:
  checker:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Repo checkout"
        uses: "actions/checkout"
      - name: "Nix Package Manager install"
        uses: "DeterminateSystems/nix-installer-action@v16"
      - name: "Flake.lock checking"
        uses: "DeterminateSystems/flake-checker-action@v5"
      - name: "Formatter run"
        run: "nix fmt"
