---
name: "Flake Check Action"
run-name: "nfc"
on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened,edited,synchronize,reopened]
    
jobs:
  checker:
    runs-on: "ubuntu-latest"
    steps:
      - name: "repo checkout"
        uses: "actions/checkout@v4"
      - name: "nix install"
        uses: "DeterminateSystems/nix-installer-action@v16"
      - name: "flake check"
        uses: "DeterminateSystems/flake-checker-action@v5"
      - name: "nix fmt"
        run: "nix fmt"
