[formatter.alejandra]
command = "alejandra"
options = [
  "--experimental-config",
  "fmtconf/alejandra.toml",
  "--check",
]
includes = [
  "."
]

[formatter.statix]
command = "statix"
options = [
  "check",
  "--config",
  "fmtconf/statix.toml",
]
includes = [
  "."
]

[formatter.deadnix]
command = "deadnix"
options = [
  "--fail",
]
includes = [
  "."
]
